lib/fullstack_web/router.ex
defmodule FullstackWeb.Router do
  use FullstackWeb, :router

  import FullstackWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FullstackWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FullstackWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", FullstackWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FullstackWeb.Telemetry, ecto_repos: [Fullstack.Repo]
    end
  end

  ## Authentication routes

  scope "/", FullstackWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", FullstackWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", FullstackWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/fullstack_web/views/layout_view.ex
defmodule FullstackWeb.LayoutView do
  use FullstackWeb, :view
end

lib/fullstack_web/templates/layout/_user_menu.html.eex
<%= if @current_user do %>
  <li class="navbar-text">
    <%= @current_user.email %>
  </li>
  <li class="nav-item">
    <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "nav-link" %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link "Log In", to: Routes.user_session_path(@conn, :new), class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "nav-link" %>
  </li>
<% end %>

lib/fullstack_web/templates/layout/app.html.eex
<main role="main" class="container mx-auto max-w-4xl px-4 lg:px-0">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/fullstack_web/templates/layout/live.html.leex
<main role="main" class="container mx-auto max-w-4xl px-4 lg:px-0">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/fullstack_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Fullstack", suffix: " Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="d-flex flex-column h-100">
    <nav class="shadow-sm navbar navbar-expand-md navbar-light bg-light fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Fullstack</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-navbar">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="main-navbar">
          <ul class="mb-2 navbar-nav me-auto mb-md-0">
            <li class="nav-item">
              <%= link "Home", to: Routes.page_path(@conn, :index), class: "nav-link" %>
            </li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li class="nav-item">
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav">
            <%= render "_user_menu.html", assigns %>
          </ul>
        </div>
      </div>
    </nav>

    <%= @inner_content %>

    <footer class="py-3 mt-auto footer bg-dark">
      <div class="container text-sm text-center text-light">
        &copy; <%= DateTime.utc_now.year %> Fullstack
      </div>
    </footer>
  </body>
</html>

lib/fullstack_web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Fullstack", suffix: " Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="d-flex flex-column h-100">
    <main role="main" class="container px-4 mb-5">
      <p class="alert alert-info alert-left toast" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger alert-left toast" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="row">
        <div class="col-lg-2"></div>
        <div class="bg-white rounded-lg shadow-lg col-lg-8">
          <div class="row">
            <div class="col-md-6" style="background-size:cover;background-image:url('https://images.unsplash.com/photo-1602610411365-76e8c2a88e18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=333&q=80')" >
            </div>

            <div class="px-4 py-5 col-md-6">
              <h2 class="text-center display-6 text-muted">Fullstack</h2>
              <%= @inner_content %>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>